"""Add secret question and answer to User model

Revision ID: a0ff351da98f
Revises: 
Create Date: 2025-04-23 20:45:00.692760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ff351da98f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_question', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('secret_answer_hash', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('secret_answer_hash')
        batch_op.drop_column('secret_question')

    # ### end Alembic commands ###
